import {
  MathObjType,
  MathTaskExplanationType,
  MathTasksType,
} from "types/addition";

const EASY_TASKS: MathTasksType = {
  missingNumberAddition: {
    tasks: [
      {
        id: "1",
        a: 1,
        b: undefined,
        result: 3,
        kind: "missingNumberAddition",
      },
      {
        id: "2",
        a: undefined,
        b: 2,
        result: 3,
        kind: "missingNumberAddition",
      },
      {
        id: "3",
        a: 1,
        b: 2,
        result: undefined,
        kind: "missingNumberAddition",
      },
      {
        id: "4",
        a: 4,
        b: 2,
        result: undefined,
        kind: "missingNumberAddition",
      },
      {
        id: "5",
        a: undefined,
        b: 4,
        result: 8,
        kind: "missingNumberAddition",
      },
      {
        id: "6",
        a: 7,
        b: undefined,
        result: 8,
        kind: "missingNumberAddition",
      },
      {
        id: "7",
        a: 1,
        b: undefined,
        result: 10,
        kind: "missingNumberAddition",
      },
      {
        id: "8",
        a: undefined,
        b: 9,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "9",
        a: 7,
        b: undefined,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "10",
        a: undefined,
        b: 8,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "11",
        a: 8,
        b: undefined,
        result: 10,
        kind: "missingNumberAddition",
      },
      {
        id: "12",
        a: undefined,
        b: 9,
        result: 10,
        kind: "missingNumberAddition",
      },
      {
        id: "13",
        a: 7,
        b: undefined,
        result: 9,
        kind: "missingNumberAddition",
      },
    ],
  },
  missingNumberSubtraction: {
    tasks: [
      {
        id: "1",
        a: 5,
        b: undefined,
        result: 3,
        kind: "missingNumberSubtraction",
      },
      {
        id: "2",
        a: undefined,
        b: 2,
        result: 3,
        kind: "missingNumberSubtraction",
      },
      {
        id: "3",
        a: 7,
        b: 2,
        result: undefined,
        kind: "missingNumberSubtraction",
      },
      {
        id: "4",
        a: 4,
        b: 2,
        result: undefined,
        kind: "missingNumberSubtraction",
      },
      {
        id: "5",
        a: undefined,
        b: 4,
        result: 4,
        kind: "missingNumberSubtraction",
      },
      {
        id: "6",
        a: 9,
        b: undefined,
        result: 8,
        kind: "missingNumberSubtraction",
      },
      {
        id: "7",
        a: 6,
        b: undefined,
        result: 4,
        kind: "missingNumberSubtraction",
      },
      {
        id: "8",
        a: undefined,
        b: 9,
        result: 1,
        kind: "missingNumberSubtraction",
      },
      {
        id: "9",
        a: 7,
        b: undefined,
        result: 2,
        kind: "missingNumberSubtraction",
      },
      {
        id: "10",
        a: undefined,
        b: 8,
        result: 0,
        kind: "missingNumberSubtraction",
      },
      {
        id: "11",
        a: 5,
        b: undefined,
        result: 2,
        kind: "missingNumberSubtraction",
      },
      {
        id: "12",
        a: undefined,
        b: 4,
        result: 1,
        kind: "missingNumberSubtraction",
      },
      {
        id: "13",
        a: 7,
        b: undefined,
        result: 2,
        kind: "missingNumberSubtraction",
      },
    ],
  },
  getResultOfAddition: {
    tasks: [
      {
        id: "1",
        a: 1,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "2",
        a: 2,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "3",
        a: 3,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "4",
        a: 4,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "5",
        a: 5,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "6",
        a: 6,
        b: 4,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "7",
        a: 7,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "8",
        a: 8,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "9",
        a: 3,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "10",
        a: 5,
        b: 5,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "11",
        a: 4,
        b: 6,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "12",
        a: 7,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "13",
        a: 1,
        b: 9,
        result: undefined,
        kind: "getResultOfAddition",
      },
    ],
  },
  getResultOfSubtraction: {
    tasks: [
      {
        id: "1",
        a: 4,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "2",
        a: 2,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "3",
        a: 3,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "4",
        a: 4,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "5",
        a: 5,
        b: 3,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "6",
        a: 10,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "7",
        a: 7,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "8",
        a: 8,
        b: 4,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "9",
        a: 10,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "10",
        a: 10,
        b: 7,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "11",
        a: 7,
        b: 4,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "12",
        a: 9,
        b: 3,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "13",
        a: 10,
        b: 9,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
    ],
  },
};

export const MATH_TASKS: MathObjType = {
  easy: EASY_TASKS,
};

export const MATH_TASK_EXPLANATION: MathTaskExplanationType = {
  getResultOfAddition: "Atrisini vienādojumu",
  getResultOfSubtraction: "Atrisini vienādojumu",
  missingNumberAddition: "Atrodi nezināmo skaitli",
  missingNumberSubtraction: "Atrodi nezināmo skaitli",
};
