import { MathTasksType } from "types/addition";

const SECOND_TASKS: MathTasksType = {
  missingNumberAddition: {
    tasks: [
      {
        id: "1",
        a: 10,
        b: undefined,
        result: 13,
        kind: "missingNumberAddition",
      },
      {
        id: "2",
        a: undefined,
        b: 12,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "3",
        a: 10,
        b: 2,
        result: undefined,
        kind: "missingNumberAddition",
      },
      {
        id: "4",
        a: 14,
        b: 2,
        result: undefined,
        kind: "missingNumberAddition",
      },
      {
        id: "5",
        a: undefined,
        b: 4,
        result: 10,
        kind: "missingNumberAddition",
      },
      {
        id: "6",
        a: 7,
        b: undefined,
        result: 11,
        kind: "missingNumberAddition",
      },
      {
        id: "7",
        a: 10,
        b: undefined,
        result: 20,
        kind: "missingNumberAddition",
      },
      {
        id: "8",
        a: undefined,
        b: 10,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "9",
        a: 7,
        b: undefined,
        result: 17,
        kind: "missingNumberAddition",
      },
      {
        id: "10",
        a: undefined,
        b: 8,
        result: 15,
        kind: "missingNumberAddition",
      },
      {
        id: "11",
        a: 8,
        b: undefined,
        result: 20,
        kind: "missingNumberAddition",
      },
      {
        id: "12",
        a: undefined,
        b: 9,
        result: 20,
        kind: "missingNumberAddition",
      },
      {
        id: "13",
        a: 7,
        b: undefined,
        result: 17,
        kind: "missingNumberAddition",
      },
    ],
  },
  missingNumberSubtraction: {
    tasks: [
      {
        id: "1",
        a: 13,
        b: undefined,
        result: 10,
        kind: "missingNumberSubtraction",
      },
      {
        id: "2",
        a: undefined,
        b: 17,
        result: 14,
        kind: "missingNumberSubtraction",
      },
      {
        id: "3",
        a: 12,
        b: 2,
        result: undefined,
        kind: "missingNumberSubtraction",
      },
      {
        id: "4",
        a: 15,
        b: 2,
        result: undefined,
        kind: "missingNumberSubtraction",
      },
      {
        id: "5",
        a: undefined,
        b: 20,
        result: 16,
        kind: "missingNumberSubtraction",
      },
      {
        id: "6",
        a: 15,
        b: undefined,
        result: 10,
        kind: "missingNumberSubtraction",
      },
      {
        id: "7",
        a: 16,
        b: undefined,
        result: 12,
        kind: "missingNumberSubtraction",
      },
      {
        id: "8",
        a: undefined,
        b: 10,
        result: 10,
        kind: "missingNumberSubtraction",
      },
      {
        id: "9",
        a: 20,
        b: undefined,
        result: 18,
        kind: "missingNumberSubtraction",
      },
      {
        id: "10",
        a: undefined,
        b: 18,
        result: 2,
        kind: "missingNumberSubtraction",
      },
      {
        id: "11",
        a: 15,
        b: undefined,
        result: 9,
        kind: "missingNumberSubtraction",
      },
      {
        id: "12",
        a: undefined,
        b: 4,
        result: 16,
        kind: "missingNumberSubtraction",
      },
      {
        id: "13",
        a: 17,
        b: undefined,
        result: 15,
        kind: "missingNumberSubtraction",
      },
    ],
  },
  getResultOfAddition: {
    tasks: [
      {
        id: "1",
        a: 10,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "2",
        a: 12,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "3",
        a: 13,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "4",
        a: 14,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "5",
        a: 15,
        b: 5,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "6",
        a: 16,
        b: 4,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "7",
        a: 17,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "8",
        a: 11,
        b: 9,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "9",
        a: 9,
        b: 11,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "10",
        a: 8,
        b: 12,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "11",
        a: 14,
        b: 6,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "12",
        a: 16,
        b: 2,
        result: undefined,
        kind: "getResultOfAddition",
      },
      {
        id: "13",
        a: 11,
        b: 4,
        result: undefined,
        kind: "getResultOfAddition",
      },
    ],
  },
  getResultOfSubtraction: {
    tasks: [
      {
        id: "1",
        a: 14,
        b: 4,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "2",
        a: 18,
        b: 3,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "3",
        a: 13,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "4",
        a: 14,
        b: 8,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "5",
        a: 15,
        b: 8,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "6",
        a: 20,
        b: 10,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "7",
        a: 17,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "8",
        a: 19,
        b: 3,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "9",
        a: 10,
        b: 2,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "10",
        a: 10,
        b: 7,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "11",
        a: 17,
        b: 4,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "12",
        a: 17,
        b: 3,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
      {
        id: "13",
        a: 20,
        b: 9,
        result: undefined,
        kind: "getResultOfSubtraction",
      },
    ],
  },
};

export default SECOND_TASKS;
